import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class", ".hacker"],
  content: [
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        // Material You tokens
        "surface-container-highest": "#e4e1e9",
        "on-primary-fixed-variant": "#8f0046",
        primary: "#b21f5d",
        "tertiary-fixed-dim": "#cebdff",
        "tertiary-fixed": "#e8ddff",
        "inverse-primary": "#ffb1c5",
        "primary-container": "#ff5e97",
        "on-primary": "#ffffff",
        "soft-lavender": "#D6BCFA",
        "tertiary-container": "#a286f5",
        "primary-fixed-dim": "#ffb1c5",
        "surface-container-lowest": "#ffffff",
        "error-container": "#ffdad6",
        "inverse-on-surface": "#f3eff7",
        "surface-container-low": "#f6f2fa",
        "on-primary-fixed": "#3f001b",
        "on-secondary": "#ffffff",
        "bubblegum-pink": "#FF5E97",
        "brutal-black": "#0E0E12",
        "surface-container": "#f0ecf4",
        outline: "#8b7076",
        "on-error": "#ffffff",
        "terminal-dim-green": "#008F24",
        "terminal-green": "#00FF41",
        "on-secondary-fixed-variant": "#005232",
        "on-surface-variant": "#584146",
        "on-secondary-fixed": "#002111",
        "surface-container-high": "#eae7ee",
        "secondary-fixed-dim": "#00e293",
        "on-tertiary": "#ffffff",
        "surface-variant": "#e4e1e9",
        "secondary-fixed": "#50ffaf",
        "on-tertiary-container": "#381385",
        "surface-dim": "#dcd9e0",
        "cyber-cyan": "#00E5FF",
        "on-tertiary-fixed": "#21005e",
        "electric-mint": "#00F5A0",
        "outline-variant": "#dfbec5",
        background: "#fbf8ff",
        "primary-fixed": "#ffd9e1",
        tertiary: "#674bb5",
        "on-primary-container": "#660030",
        "inverse-surface": "#303035",
        "terminal-black": "#050505",
        "acid-yellow": "#FFE600",
        "on-background": "#1b1b20",
        "on-surface": "#1b1b20",
        surface: "#fbf8ff",
        secondary: "#006c44",
        "surface-bright": "#fbf8ff",
        "canvas-cream": "#FDFBF7",
        "on-secondary-container": "#007147",
        "on-tertiary-fixed-variant": "#4f319c",
        "on-error-container": "#93000a",
        "secondary-container": "#25fea8",
        error: "#ba1a1a",
        "surface-tint": "#b21f5d",
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        "space-xl": "3rem",
        "space-sm": "0.5rem",
        margin: "2.5rem",
        "space-md": "1rem",
        "space-lg": "1.75rem",
        "margin-mobile": "1.25rem",
        gutter: "1.5rem",
        "space-xs": "0.25rem",
        "gutter-mobile": "1rem",
      },
      fontFamily: {
        "label-sm": ["Space Mono", "monospace"],
        "headline-md": ["Anton", "sans-serif"],
        "display-xl-mobile": ["Anton", "sans-serif"],
        "body-md": ["JetBrains Mono", "monospace"],
        "headline-lg": ["Anton", "sans-serif"],
        "body-lg": ["JetBrains Mono", "monospace"],
        "display-lg-mobile": ["Anton", "sans-serif"],
        "display-lg": ["Anton", "sans-serif"],
        "label-lg": ["Space Mono", "monospace"],
        "body-sm": ["JetBrains Mono", "monospace"],
        "display-xl": ["Anton", "sans-serif"],
        "label-md": ["Space Mono", "monospace"],
        anton: ["Anton", "sans-serif"],
        "jetbrains-mono": ["JetBrains Mono", "monospace"],
        "space-mono": ["Space Mono", "monospace"],
      },
      fontSize: {
        "label-sm": [
          "10px",
          { lineHeight: "14px", letterSpacing: "0.12em", fontWeight: "700" },
        ],
        "headline-md": [
          "32px",
          { lineHeight: "36px", letterSpacing: "0.03em", fontWeight: "400" },
        ],
        "display-xl-mobile": [
          "56px",
          { lineHeight: "56px", letterSpacing: "0.02em", fontWeight: "400" },
        ],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": [
          "44px",
          { lineHeight: "48px", letterSpacing: "0.02em", fontWeight: "400" },
        ],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "500" }],
        "display-lg-mobile": [
          "40px",
          { lineHeight: "44px", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "display-lg": [
          "72px",
          { lineHeight: "72px", letterSpacing: "0.01em", fontWeight: "400" },
        ],
        "label-lg": [
          "14px",
          { lineHeight: "18px", letterSpacing: "0.08em", fontWeight: "700" },
        ],
        "body-sm": ["13px", { lineHeight: "20px", fontWeight: "400" }],
        "display-xl": [
          "112px",
          { lineHeight: "100px", letterSpacing: "0.02em", fontWeight: "400" },
        ],
        "label-md": [
          "12px",
          { lineHeight: "16px", letterSpacing: "0.1em", fontWeight: "700" },
        ],
      },
      keyframes: {
        marquee: {
          "0%": { transform: "translateX(0%)" },
          "100%": { transform: "translateX(-50%)" },
        },
        "marquee-reverse": {
          "0%": { transform: "translateX(-50%)" },
          "100%": { transform: "translateX(0%)" },
        },
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-12px)" },
        },
        "glitch-1": {
          "0%, 100%": { transform: "translate(0, 0)", opacity: "0.8" },
          "20%": { transform: "translate(-2px, 1px)", opacity: "0.8" },
          "40%": { transform: "translate(2px, -1px)", opacity: "0.8" },
          "60%": { transform: "translate(-1px, 2px)", opacity: "0.8" },
          "80%": { transform: "translate(1px, -2px)", opacity: "0.8" },
        },
        "glitch-2": {
          "0%, 100%": { transform: "translate(0, 0)", opacity: "0.8" },
          "20%": { transform: "translate(2px, -1px)", opacity: "0.8" },
          "40%": { transform: "translate(-2px, 1px)", opacity: "0.8" },
          "60%": { transform: "translate(1px, -2px)", opacity: "0.8" },
          "80%": { transform: "translate(-1px, 2px)", opacity: "0.8" },
        },
        "spin-vinyl": {
          from: { transform: "rotate(0deg)" },
          to: { transform: "rotate(360deg)" },
        },
        "eq-bar-1": {
          "0%, 100%": { height: "8px" },
          "50%": { height: "20px" },
        },
        "eq-bar-2": {
          "0%, 100%": { height: "16px" },
          "33%": { height: "4px" },
          "66%": { height: "24px" },
        },
        "eq-bar-3": {
          "0%, 100%": { height: "12px" },
          "25%": { height: "24px" },
          "75%": { height: "6px" },
        },
        scanline: {
          "0%": { transform: "translateY(-100%)" },
          "100%": { transform: "translateY(100%)" },
        },
        "hacker-flicker": {
          "0%, 19%, 21%, 23%, 25%, 54%, 56%, 100%": { opacity: "1" },
          "20%, 24%, 55%": { opacity: "0" },
        },
        ping: {
          "75%, 100%": { transform: "scale(2)", opacity: "0" },
        },
      },
      animation: {
        marquee: "marquee 20s linear infinite",
        "marquee-reverse": "marquee-reverse 25s linear infinite",
        "marquee-slow": "marquee 35s linear infinite",
        float: "float 3s ease-in-out infinite",
        "glitch-1": "glitch-1 3s infinite",
        "glitch-2": "glitch-2 3s infinite 0.1s",
        "spin-vinyl": "spin-vinyl 3s linear infinite",
        "eq-bar-1": "eq-bar-1 0.6s ease-in-out infinite",
        "eq-bar-2": "eq-bar-2 0.8s ease-in-out infinite 0.1s",
        "eq-bar-3": "eq-bar-3 0.7s ease-in-out infinite 0.2s",
        scanline: "scanline 3s linear infinite",
        "hacker-flicker": "hacker-flicker 5s linear infinite",
        ping: "ping 1s cubic-bezier(0, 0, 0.2, 1) infinite",
      },
    },
  },
  plugins: [],
};

export default config;
